### ISSUE TITLE
Specify documentation for session related services

### ISSUE THREAD

**Issue by milikicn** [faculty-of-organizational-sciences/open-parliament-api#10]
Similarly to the services related to members and parties, specify how services related to sessions should work. Here, there should be:
- a service for retrieving all sessions '/sessions'. There should be query parameters ''dateFrom', 'dateTo', 'limit' and 'offset'
- a service for retrieving information about a specific session '/sessions/:id'.

**Comment by marijamilcic** [comment]
closed #10
